#!/bin/bash

# Enable i2c - needed for the Display-O-Tron HAT
modprobe i2c-dev

# Run once the first time
python src/python/start.py

# Start resin-wifi-connect
export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

sleep 1 # Delay needed to avoid DBUS introspection errors

node src/app.js --clear=false

# At this point the WiFi connection has been configured and the device has
# internet - unless the configured WiFi connection is no longer available.

# Run once connection_status
python src/python/connection_status.py

# Start the main application
#python src/python/main.py

# Start rabbitmq
sudo rabbitmq-server service start -detached

sleep 40 # Delay needed to avoid MQTT connection errors

# Run one process loop
python src/python/subscribe_MQTT.py
